### ISSUE TITLE
Sync interval option doesn't work (mismatch with name in libsql Database constructor)

### ISSUE THREAD

**Issue by Hedrekao** [tursodatabase/libsql-client-ts#203]
When trying to create client with sync interval, in reality automatic periodic syncs never happen, due to the fact that in sqlite3.js file, following object is passed to Database constructor:

![image](https://github.com/tursodatabase/libsql-client-ts/assets/82450784/41a5550c-e402-4740-8599-afdc38c7e625)
However, constructor in file index.js from libsql package expects field `syncPeriod` instead of `syncInterval`

![image](https://github.com/tursodatabase/libsql-client-ts/assets/82450784/679f251a-04a4-4b31-999d-f420d91a4901)

Therefore value of `syncPeriod` is set to 0 and db doesn't do any automatic periodic syncs.

**Comment by sudhir-b** [comment]
I'd love to try to fix this in a PR - is it sufficient to update `options` so that it passes through `syncPeriod: config.syncInterval`, or is it more correct to change the whole interface so that we replace `syncInterval` with `syncPeriod` everywhere? The `syncInterval` option has made its way into docs which makes me think the former option is the preferred approach

**Comment by sudhir-b** [comment]
Opened PR #209 for this
